services:
    # Frontend modules
    Mindbird\Contao\Company\Controller\CompanyListController:
        arguments:
            - "@mindbird.contao.company_service"
        tags:
            - { name: contao.frontend_module, category: companies }

    Mindbird\Contao\Company\Controller\CompanyFilterController:
        tags:
            - { name: contao.frontend_module, category: companies }

    Mindbird\Contao\Company\Controller\CompanyMapController:
        arguments:
            - "@mindbird.contao.company_service"
        tags:
            - { name: contao.frontend_module, category: companies }

    Mindbird\Contao\Company\Controller\CompanyDetailController:
        tags:
            - { name: contao.frontend_module, category: companies }

    # Services
    mindbird.contao.company_service:
        class: Mindbird\Contao\Company\Services\CompanyService

    Mindbird\Contao\Company\Services\CompanyService: '@mindbird.contao.company_service'
